---
- name: install packages 
  action: yum name={{ item }} state=installed
  with_items:
   - opennebula-sunstone
   - memcached

- name: start and enable sunstone and memcache
  action: service name={{ item }} state=started enabled=true
  with_items:
   - memcached
   - httpd
- name: install Ruby memcache client
  action: gem name=memcache-client state=present

- name: configure apache for Sunstone
  action: template src=one_sunstone.conf.j2 dest=/etc/httpd/conf.d/one_sunstone.conf
  notify: restart httpd
  
- name: start sunstone
  action: service name=opennebula-sunstone state=started enabled=true


